/*
 * Partial Unicode character names. The full list (UnicodeData.txt) is about 2 MB, so this holds
 * a curated subset, written out from the Unicode Character Database (unicode.org/Public/UCD/latest/
 * ucd/UnicodeData.txt and NameAliases.txt):
 *   ASCII and C1 controls (by their alias, as their formal name is <control>), printable ASCII,
 *   Latin-1 Supplement, Latin Extended-A, basic Greek and Cyrillic, General Punctuation, spaces,
 *   invisible and format characters, variation selectors, tag characters, fullwidth ASCII,
 *   a few common combining marks and symbols.
 * Names that follow a rule are computed: CJK unified ideographs, Hangul syllables (Unicode
 * chapter 3.12), variation selectors, tags and fullwidth forms.
 */

const C0 =
	'NULL|START OF HEADING|START OF TEXT|END OF TEXT|END OF TRANSMISSION|ENQUIRY|ACKNOWLEDGE|ALERT|BACKSPACE|CHARACTER TABULATION|LINE FEED|LINE TABULATION|FORM FEED|CARRIAGE RETURN|SHIFT OUT|SHIFT IN|DATA LINK ESCAPE|DEVICE CONTROL ONE|DEVICE CONTROL TWO|DEVICE CONTROL THREE|DEVICE CONTROL FOUR|NEGATIVE ACKNOWLEDGE|SYNCHRONOUS IDLE|END OF TRANSMISSION BLOCK|CANCEL|END OF MEDIUM|SUBSTITUTE|ESCAPE|INFORMATION SEPARATOR FOUR|INFORMATION SEPARATOR THREE|INFORMATION SEPARATOR TWO|INFORMATION SEPARATOR ONE'.split(
		'|'
	);
const C1 =
	'PADDING CHARACTER|HIGH OCTET PRESET|BREAK PERMITTED HERE|NO BREAK HERE|INDEX|NEXT LINE|START OF SELECTED AREA|END OF SELECTED AREA|CHARACTER TABULATION SET|CHARACTER TABULATION WITH JUSTIFICATION|LINE TABULATION SET|PARTIAL LINE FORWARD|PARTIAL LINE BACKWARD|REVERSE LINE FEED|SINGLE SHIFT TWO|SINGLE SHIFT THREE|DEVICE CONTROL STRING|PRIVATE USE ONE|PRIVATE USE TWO|SET TRANSMIT STATE|CANCEL CHARACTER|MESSAGE WAITING|START OF GUARDED AREA|END OF GUARDED AREA|START OF STRING|SINGLE GRAPHIC CHARACTER INTRODUCER|SINGLE CHARACTER INTRODUCER|CONTROL SEQUENCE INTRODUCER|STRING TERMINATOR|OPERATING SYSTEM COMMAND|PRIVACY MESSAGE|APPLICATION PROGRAM COMMAND'.split(
		'|'
	);

const ASCII_PUNCT: Record<string, string> = {
	' ': 'SPACE',
	'!': 'EXCLAMATION MARK',
	'"': 'QUOTATION MARK',
	'#': 'NUMBER SIGN',
	$: 'DOLLAR SIGN',
	'%': 'PERCENT SIGN',
	'&': 'AMPERSAND',
	"'": 'APOSTROPHE',
	'(': 'LEFT PARENTHESIS',
	')': 'RIGHT PARENTHESIS',
	'*': 'ASTERISK',
	'+': 'PLUS SIGN',
	',': 'COMMA',
	'-': 'HYPHEN-MINUS',
	'.': 'FULL STOP',
	'/': 'SOLIDUS',
	':': 'COLON',
	';': 'SEMICOLON',
	'<': 'LESS-THAN SIGN',
	'=': 'EQUALS SIGN',
	'>': 'GREATER-THAN SIGN',
	'?': 'QUESTION MARK',
	'@': 'COMMERCIAL AT',
	'[': 'LEFT SQUARE BRACKET',
	'\\': 'REVERSE SOLIDUS',
	']': 'RIGHT SQUARE BRACKET',
	'^': 'CIRCUMFLEX ACCENT',
	_: 'LOW LINE',
	'`': 'GRAVE ACCENT',
	'{': 'LEFT CURLY BRACKET',
	'|': 'VERTICAL LINE',
	'}': 'RIGHT CURLY BRACKET',
	'~': 'TILDE'
};

const DIGITS = 'ZERO ONE TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE'.split(' ');

/** Explicit names, keyed by code point in hex. */
const TABLE = `
A0 NO-BREAK SPACE
A1 INVERTED EXCLAMATION MARK
A2 CENT SIGN
A3 POUND SIGN
A4 CURRENCY SIGN
A5 YEN SIGN
A6 BROKEN BAR
A7 SECTION SIGN
A8 DIAERESIS
A9 COPYRIGHT SIGN
AA FEMININE ORDINAL INDICATOR
AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
AC NOT SIGN
AD SOFT HYPHEN
AE REGISTERED SIGN
AF MACRON
B0 DEGREE SIGN
B1 PLUS-MINUS SIGN
B2 SUPERSCRIPT TWO
B3 SUPERSCRIPT THREE
B4 ACUTE ACCENT
B5 MICRO SIGN
B6 PILCROW SIGN
B7 MIDDLE DOT
B8 CEDILLA
B9 SUPERSCRIPT ONE
BA MASCULINE ORDINAL INDICATOR
BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
BC VULGAR FRACTION ONE QUARTER
BD VULGAR FRACTION ONE HALF
BE VULGAR FRACTION THREE QUARTERS
BF INVERTED QUESTION MARK
C6 LATIN CAPITAL LETTER AE
D0 LATIN CAPITAL LETTER ETH
D7 MULTIPLICATION SIGN
D8 LATIN CAPITAL LETTER O WITH STROKE
DE LATIN CAPITAL LETTER THORN
DF LATIN SMALL LETTER SHARP S
E6 LATIN SMALL LETTER AE
F0 LATIN SMALL LETTER ETH
F7 DIVISION SIGN
F8 LATIN SMALL LETTER O WITH STROKE
FE LATIN SMALL LETTER THORN
110 LATIN CAPITAL LETTER D WITH STROKE
111 LATIN SMALL LETTER D WITH STROKE
126 LATIN CAPITAL LETTER H WITH STROKE
127 LATIN SMALL LETTER H WITH STROKE
131 LATIN SMALL LETTER DOTLESS I
132 LATIN CAPITAL LIGATURE IJ
133 LATIN SMALL LIGATURE IJ
138 LATIN SMALL LETTER KRA
13F LATIN CAPITAL LETTER L WITH MIDDLE DOT
140 LATIN SMALL LETTER L WITH MIDDLE DOT
141 LATIN CAPITAL LETTER L WITH STROKE
142 LATIN SMALL LETTER L WITH STROKE
149 LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
14A LATIN CAPITAL LETTER ENG
14B LATIN SMALL LETTER ENG
152 LATIN CAPITAL LIGATURE OE
153 LATIN SMALL LIGATURE OE
166 LATIN CAPITAL LETTER T WITH STROKE
167 LATIN SMALL LETTER T WITH STROKE
17F LATIN SMALL LETTER LONG S
251 LATIN SMALL LETTER ALPHA
261 LATIN SMALL LETTER SCRIPT G
269 LATIN SMALL LETTER IOTA
300 COMBINING GRAVE ACCENT
301 COMBINING ACUTE ACCENT
302 COMBINING CIRCUMFLEX ACCENT
303 COMBINING TILDE
304 COMBINING MACRON
306 COMBINING BREVE
307 COMBINING DOT ABOVE
308 COMBINING DIAERESIS
30A COMBINING RING ABOVE
30B COMBINING DOUBLE ACUTE ACCENT
30C COMBINING CARON
323 COMBINING DOT BELOW
327 COMBINING CEDILLA
328 COMBINING OGONEK
336 COMBINING LONG STROKE OVERLAY
338 COMBINING LONG SOLIDUS OVERLAY
34F COMBINING GRAPHEME JOINER
37E GREEK QUESTION MARK
3C2 GREEK SMALL LETTER FINAL SIGMA
4AE CYRILLIC CAPITAL LETTER STRAIGHT U
4AF CYRILLIC SMALL LETTER STRAIGHT U
4BB CYRILLIC SMALL LETTER SHHA
4CF CYRILLIC SMALL LETTER PALOCHKA
501 CYRILLIC SMALL LETTER KOMI DE
51A CYRILLIC CAPITAL LETTER QA
51B CYRILLIC SMALL LETTER QA
51C CYRILLIC CAPITAL LETTER WE
51D CYRILLIC SMALL LETTER WE
405 CYRILLIC CAPITAL LETTER DZE
406 CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
408 CYRILLIC CAPITAL LETTER JE
455 CYRILLIC SMALL LETTER DZE
456 CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
458 CYRILLIC SMALL LETTER JE
570 ARMENIAN SMALL LETTER HO
578 ARMENIAN SMALL LETTER VO
57D ARMENIAN SMALL LETTER SEH
585 ARMENIAN SMALL LETTER OH
61C ARABIC LETTER MARK
115F HANGUL CHOSEONG FILLER
1160 HANGUL JUNGSEONG FILLER
1680 OGHAM SPACE MARK
17B4 KHMER VOWEL INHERENT AQ
17B5 KHMER VOWEL INHERENT AA
180E MONGOLIAN VOWEL SEPARATOR
2000 EN QUAD
2001 EM QUAD
2002 EN SPACE
2003 EM SPACE
2004 THREE-PER-EM SPACE
2005 FOUR-PER-EM SPACE
2006 SIX-PER-EM SPACE
2007 FIGURE SPACE
2008 PUNCTUATION SPACE
2009 THIN SPACE
200A HAIR SPACE
200B ZERO WIDTH SPACE
200C ZERO WIDTH NON-JOINER
200D ZERO WIDTH JOINER
200E LEFT-TO-RIGHT MARK
200F RIGHT-TO-LEFT MARK
2010 HYPHEN
2011 NON-BREAKING HYPHEN
2012 FIGURE DASH
2013 EN DASH
2014 EM DASH
2015 HORIZONTAL BAR
2016 DOUBLE VERTICAL LINE
2017 DOUBLE LOW LINE
2018 LEFT SINGLE QUOTATION MARK
2019 RIGHT SINGLE QUOTATION MARK
201A SINGLE LOW-9 QUOTATION MARK
201B SINGLE HIGH-REVERSED-9 QUOTATION MARK
201C LEFT DOUBLE QUOTATION MARK
201D RIGHT DOUBLE QUOTATION MARK
201E DOUBLE LOW-9 QUOTATION MARK
201F DOUBLE HIGH-REVERSED-9 QUOTATION MARK
2020 DAGGER
2021 DOUBLE DAGGER
2022 BULLET
2023 TRIANGULAR BULLET
2024 ONE DOT LEADER
2025 TWO DOT LEADER
2026 HORIZONTAL ELLIPSIS
2027 HYPHENATION POINT
2028 LINE SEPARATOR
2029 PARAGRAPH SEPARATOR
202A LEFT-TO-RIGHT EMBEDDING
202B RIGHT-TO-LEFT EMBEDDING
202C POP DIRECTIONAL FORMATTING
202D LEFT-TO-RIGHT OVERRIDE
202E RIGHT-TO-LEFT OVERRIDE
202F NARROW NO-BREAK SPACE
2030 PER MILLE SIGN
2031 PER TEN THOUSAND SIGN
2032 PRIME
2033 DOUBLE PRIME
2034 TRIPLE PRIME
2035 REVERSED PRIME
2039 SINGLE LEFT-POINTING ANGLE QUOTATION MARK
203A SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
203B REFERENCE MARK
203C DOUBLE EXCLAMATION MARK
203D INTERROBANG
2044 FRACTION SLASH
2047 DOUBLE QUESTION MARK
2048 QUESTION EXCLAMATION MARK
2049 EXCLAMATION QUESTION MARK
205F MEDIUM MATHEMATICAL SPACE
2060 WORD JOINER
2061 FUNCTION APPLICATION
2062 INVISIBLE TIMES
2063 INVISIBLE SEPARATOR
2064 INVISIBLE PLUS
2066 LEFT-TO-RIGHT ISOLATE
2067 RIGHT-TO-LEFT ISOLATE
2068 FIRST STRONG ISOLATE
2069 POP DIRECTIONAL ISOLATE
206A INHIBIT SYMMETRIC SWAPPING
206B ACTIVATE SYMMETRIC SWAPPING
206C INHIBIT ARABIC FORM SHAPING
206D ACTIVATE ARABIC FORM SHAPING
206E NATIONAL DIGIT SHAPES
206F NOMINAL DIGIT SHAPES
20AC EURO SIGN
20E3 COMBINING ENCLOSING KEYCAP
2116 NUMERO SIGN
2122 TRADE MARK SIGN
2190 LEFTWARDS ARROW
2191 UPWARDS ARROW
2192 RIGHTWARDS ARROW
2193 DOWNWARDS ARROW
2212 MINUS SIGN
2215 DIVISION SLASH
2713 CHECK MARK
2800 BRAILLE PATTERN BLANK
3000 IDEOGRAPHIC SPACE
3164 HANGUL FILLER
FEFF ZERO WIDTH NO-BREAK SPACE
FFA0 HALFWIDTH HANGUL FILLER
FFF9 INTERLINEAR ANNOTATION ANCHOR
FFFA INTERLINEAR ANNOTATION SEPARATOR
FFFB INTERLINEAR ANNOTATION TERMINATOR
FFFC OBJECT REPLACEMENT CHARACTER
FFFD REPLACEMENT CHARACTER
1D159 MUSICAL SYMBOL NULL NOTEHEAD
1D173 MUSICAL SYMBOL BEGIN BEAM
1D174 MUSICAL SYMBOL END BEAM
1D175 MUSICAL SYMBOL BEGIN TIE
1D176 MUSICAL SYMBOL END TIE
1D177 MUSICAL SYMBOL BEGIN SLUR
1D178 MUSICAL SYMBOL END SLUR
1D179 MUSICAL SYMBOL BEGIN PHRASE
1D17A MUSICAL SYMBOL END PHRASE
1F3FB EMOJI MODIFIER FITZPATRICK TYPE-1-2
1F3FC EMOJI MODIFIER FITZPATRICK TYPE-3
1F3FD EMOJI MODIFIER FITZPATRICK TYPE-4
1F3FE EMOJI MODIFIER FITZPATRICK TYPE-5
1F3FF EMOJI MODIFIER FITZPATRICK TYPE-6
E0001 LANGUAGE TAG
E007F CANCEL TAG
`;

const explicit = new Map<number, string>(
	TABLE.trim()
		.split('\n')
		.map((l) => {
			const i = l.indexOf(' ');
			return [parseInt(l.slice(0, i), 16), l.slice(i + 1)];
		})
);

// Greek and Cyrillic basic letters in code point order (U+0391.., U+0410..).
const GREEK =
	'ALPHA BETA GAMMA DELTA EPSILON ZETA ETA THETA IOTA KAPPA LAMDA MU NU XI OMICRON PI RHO - SIGMA TAU UPSILON PHI CHI PSI OMEGA'.split(
		' '
	);
const CYRILLIC =
	'A|BE|VE|GHE|DE|IE|ZHE|ZE|I|SHORT I|KA|EL|EM|EN|O|PE|ER|ES|TE|U|EF|HA|TSE|CHE|SHA|SHCHA|HARD SIGN|YERU|SOFT SIGN|E|YU|YA'.split(
		'|'
	);

// Accent names used for precomposed Latin letters (decomposed with NFD).
const MARKS: Record<number, string> = {
	0x300: 'GRAVE',
	0x301: 'ACUTE',
	0x302: 'CIRCUMFLEX',
	0x303: 'TILDE',
	0x304: 'MACRON',
	0x306: 'BREVE',
	0x307: 'DOT ABOVE',
	0x308: 'DIAERESIS',
	0x30a: 'RING ABOVE',
	0x30b: 'DOUBLE ACUTE',
	0x30c: 'CARON',
	0x327: 'CEDILLA',
	0x328: 'OGONEK'
};

function latinName(cp: number): string | undefined {
	const d = String.fromCodePoint(cp).normalize('NFD');
	const cps = Array.from(d).map((c) => c.codePointAt(0)!);
	if (cps.length < 2 || !/^[A-Za-z]$/.test(d[0])) return undefined;
	const marks = cps.slice(1).map((m) => MARKS[m]);
	if (marks.some((m) => !m)) return undefined;
	const upper = d[0] === d[0].toUpperCase();
	return `LATIN ${upper ? 'CAPITAL' : 'SMALL'} LETTER ${d[0].toUpperCase()} WITH ${marks.join(' AND ')}`;
}

function asciiName(cp: number): string | undefined {
	const c = String.fromCharCode(cp);
	if (cp >= 0x30 && cp <= 0x39) return `DIGIT ${DIGITS[cp - 0x30]}`;
	if (cp >= 0x41 && cp <= 0x5a) return `LATIN CAPITAL LETTER ${c}`;
	if (cp >= 0x61 && cp <= 0x7a) return `LATIN SMALL LETTER ${c.toUpperCase()}`;
	return ASCII_PUNCT[c];
}

const JAMO_L = 'G GG N D DD R M B BB S SS  J JJ C K T P H'.split(' ');
const JAMO_V = 'A AE YA YAE EO E YEO YE O WA WAE OE YO U WEO WE WI YU EU YI I'.split(' ');
const JAMO_T = ' G GG GS N NJ NH D L LG LM LB LS LT LP LH M B BS S SS NG J C K T P H'.split(' ');

/** Unicode name or alias for a code point, or undefined when it is not in the partial table. */
export function charName(cp: number): string | undefined {
	if (cp < 0x20) return `<control> ${C0[cp]}`;
	if (cp < 0x7f) return asciiName(cp);
	if (cp === 0x7f) return '<control> DELETE';
	if (cp >= 0x80 && cp <= 0x9f) return `<control> ${C1[cp - 0x80]}`;
	const e = explicit.get(cp);
	if (e) return e;
	if (cp >= 0xc0 && cp <= 0x17f) return latinName(cp);
	if (cp >= 0x391 && cp <= 0x3a9 && GREEK[cp - 0x391] !== '-')
		return `GREEK CAPITAL LETTER ${GREEK[cp - 0x391]}`;
	if (cp >= 0x3b1 && cp <= 0x3c9) return `GREEK SMALL LETTER ${GREEK[cp - 0x3b1]}`;
	if (cp >= 0x410 && cp <= 0x42f) return `CYRILLIC CAPITAL LETTER ${CYRILLIC[cp - 0x410]}`;
	if (cp >= 0x430 && cp <= 0x44f) return `CYRILLIC SMALL LETTER ${CYRILLIC[cp - 0x430]}`;
	if (cp >= 0xfe00 && cp <= 0xfe0f) return `VARIATION SELECTOR-${cp - 0xfe00 + 1}`;
	if (cp >= 0xe0100 && cp <= 0xe01ef) return `VARIATION SELECTOR-${cp - 0xe0100 + 17}`;
	if (cp >= 0xe0020 && cp <= 0xe007e) return `TAG ${asciiName(cp - 0xe0000)}`;
	if (cp >= 0xff01 && cp <= 0xff5e) return `FULLWIDTH ${asciiName(cp - 0xfee0)}`;
	if (cp >= 0xac00 && cp <= 0xd7a3) {
		const s = cp - 0xac00;
		return `HANGUL SYLLABLE ${JAMO_L[Math.floor(s / 588)]}${JAMO_V[Math.floor((s % 588) / 28)]}${JAMO_T[s % 28]}`;
	}
	if ((cp < 0xf900 || cp > 0xfaff) && /\p{Unified_Ideograph}/u.test(String.fromCodePoint(cp)))
		return `CJK UNIFIED IDEOGRAPH-${cp.toString(16).toUpperCase()}`;
	return undefined;
}
