/**
 * IBAN lengths by country code, from the SWIFT IBAN Registry (ISO 13616), published at
 * https://www.swift.com/standards/data-standards/iban-international-bank-account-number
 * Covers EU/EEA, the UK, Switzerland and the other registry countries we are confident about.
 * Countries not listed are still checked with mod 97, but not for length.
 */
export const ibanLengths: Record<string, { name: string; length: number }> = {
	AD: { name: 'Andorra', length: 24 },
	AE: { name: 'United Arab Emirates', length: 23 },
	AL: { name: 'Albania', length: 28 },
	AT: { name: 'Austria', length: 20 },
	AZ: { name: 'Azerbaijan', length: 28 },
	BA: { name: 'Bosnia and Herzegovina', length: 20 },
	BE: { name: 'Belgium', length: 16 },
	BG: { name: 'Bulgaria', length: 22 },
	BH: { name: 'Bahrain', length: 22 },
	BR: { name: 'Brazil', length: 29 },
	BY: { name: 'Belarus', length: 28 },
	CH: { name: 'Switzerland', length: 21 },
	CR: { name: 'Costa Rica', length: 22 },
	CY: { name: 'Cyprus', length: 28 },
	CZ: { name: 'Czechia', length: 24 },
	DE: { name: 'Germany', length: 22 },
	DK: { name: 'Denmark', length: 18 },
	DO: { name: 'Dominican Republic', length: 28 },
	EE: { name: 'Estonia', length: 20 },
	EG: { name: 'Egypt', length: 29 },
	ES: { name: 'Spain', length: 24 },
	FI: { name: 'Finland', length: 18 },
	FO: { name: 'Faroe Islands', length: 18 },
	FR: { name: 'France', length: 27 },
	GB: { name: 'United Kingdom', length: 22 },
	GE: { name: 'Georgia', length: 22 },
	GI: { name: 'Gibraltar', length: 23 },
	GL: { name: 'Greenland', length: 18 },
	GR: { name: 'Greece', length: 27 },
	GT: { name: 'Guatemala', length: 28 },
	HR: { name: 'Croatia', length: 21 },
	HU: { name: 'Hungary', length: 28 },
	IE: { name: 'Ireland', length: 22 },
	IL: { name: 'Israel', length: 23 },
	IQ: { name: 'Iraq', length: 23 },
	IS: { name: 'Iceland', length: 26 },
	IT: { name: 'Italy', length: 27 },
	JO: { name: 'Jordan', length: 30 },
	KW: { name: 'Kuwait', length: 30 },
	KZ: { name: 'Kazakhstan', length: 20 },
	LB: { name: 'Lebanon', length: 28 },
	LC: { name: 'Saint Lucia', length: 32 },
	LI: { name: 'Liechtenstein', length: 21 },
	LT: { name: 'Lithuania', length: 20 },
	LU: { name: 'Luxembourg', length: 20 },
	LV: { name: 'Latvia', length: 21 },
	LY: { name: 'Libya', length: 25 },
	MC: { name: 'Monaco', length: 27 },
	MD: { name: 'Moldova', length: 24 },
	ME: { name: 'Montenegro', length: 22 },
	MK: { name: 'North Macedonia', length: 19 },
	MR: { name: 'Mauritania', length: 27 },
	MT: { name: 'Malta', length: 31 },
	MU: { name: 'Mauritius', length: 30 },
	NL: { name: 'Netherlands', length: 18 },
	NO: { name: 'Norway', length: 15 },
	PK: { name: 'Pakistan', length: 24 },
	PL: { name: 'Poland', length: 28 },
	PS: { name: 'Palestine', length: 29 },
	PT: { name: 'Portugal', length: 25 },
	QA: { name: 'Qatar', length: 29 },
	RO: { name: 'Romania', length: 24 },
	RS: { name: 'Serbia', length: 22 },
	SA: { name: 'Saudi Arabia', length: 24 },
	SC: { name: 'Seychelles', length: 31 },
	SD: { name: 'Sudan', length: 18 },
	SE: { name: 'Sweden', length: 24 },
	SI: { name: 'Slovenia', length: 19 },
	SK: { name: 'Slovakia', length: 24 },
	SM: { name: 'San Marino', length: 27 },
	ST: { name: 'Sao Tome and Principe', length: 25 },
	SV: { name: 'El Salvador', length: 28 },
	TL: { name: 'Timor-Leste', length: 23 },
	TN: { name: 'Tunisia', length: 24 },
	TR: { name: 'Turkey', length: 26 },
	UA: { name: 'Ukraine', length: 29 },
	VA: { name: 'Vatican City', length: 22 },
	VG: { name: 'British Virgin Islands', length: 24 },
	XK: { name: 'Kosovo', length: 20 }
};
